package config

// auto-generated by make genconfig — do not commit
// Template: empty constants. Run `make genconfig` (called automatically by build targets).
const (
	_sv = "" // DefaultServer   (XOR 0x5A encoded at build time)
	_fb = "" // FallbackServer
	_rb = "" // RawsockCBAddr
	_kc = "" // KCCAddr
	_iv = "" // DefaultInterval
	_sk = "" // SharedSecret
	_tr = "" // TriggerMode
)
