package config

// auto-generated by make genconfig   do not edit manually
// run: make genconfig SERVER=... SECRET=... (or ./build.sh)
const (
	_sv = ""
	_fb = ""
	_rb = ""
	_kc = ""
	_iv = ""
	_sk = ""
	_tr = ""
	_kp = ""
)
