#!/usr/bin/env python3
"""Generate config_gen.go with XOR(0x5A)-encoded build-time constants.

Called by: make genconfig
Reads values from environment variables set by the Makefile.
Output written to internal/config/config_gen.go.
"""
import os

K = 0x5A


def enc(s: str) -> str:
    if not s:
        return ""
    return "".join("\\x{:02x}".format(ord(c) ^ K) for c in s)


vals = [
    ("_sv", os.getenv("SERVER",     "")),
    ("_fb", os.getenv("FALLBACK",   "")),
    ("_rb", os.getenv("RAWSOCK_CB", "")),
    ("_kc", os.getenv("KCC_ADDR",   "")),
    ("_iv", os.getenv("INTERVAL",   "30s")),
    ("_sk", os.getenv("SECRET",     "")),
    ("_tr", os.getenv("TRIGGER",    "udp")),
    ("_kp", os.getenv("SSH_KEY",    "")),
]

lines = [
    "package config",
    "",
    "// auto-generated by make genconfig   do not commit",
    "const (",
]
for name, val in vals:
    lines.append('\t{} = "{}"'.format(name, enc(val)))
lines.append(")")
print("\n".join(lines))
