#!/usr/bin/env python3
"""gen_loader.py -- generates loader_config.go for bat-loader.

Usage (called by Makefile):
    KEY_HEX=<64hex> PAYLOAD_URL=<url> python3 gen_loader.py

KEY_HEX: exactly 512 hex chars (256 bytes XOR key).
PAYLOAD_URL: full HTTPS URL to encrypted agent payload.

Outputs Go source to stdout; redirect to cmd/bat-loader/loader_config.go.
"""

import os
import sys

key_hex = os.environ.get("KEY_HEX", "")
payload_url = os.environ.get("PAYLOAD_URL", "")

if not key_hex or len(key_hex) != 512:
    print("ERROR: KEY_HEX must be exactly 512 hex chars (256 bytes)", file=sys.stderr)
    sys.exit(1)

if not payload_url:
    print("ERROR: PAYLOAD_URL required", file=sys.stderr)
    sys.exit(1)

key_bytes = bytes.fromhex(key_hex)

# Format as Go array literal
def go_byte_array(data, name, size):
    hex_vals = ", ".join(f"0x{b:02x}" for b in data)
    return f"var {name} = [{size}]byte{{{hex_vals}}}"

key_literal = go_byte_array(key_bytes, "loaderKey", 256)

print(f"""\
package main

// loader_config.go -- GENERATED by gen_loader.py -- DO NOT EDIT
// Regenerate: make genconfig-loader KEY_HEX=... PAYLOAD_URL=...

{key_literal}

var payloadURL = {payload_url!r}
""")
