package main

// loader_config.go -- generated by internal/config/gen_loader.py
// Overwritten at build time: make genconfig-loader KEY_HEX=... PAYLOAD_URL=...
// Stub values (zeroed key + empty URL) cause loader to exit cleanly -- safe for dev builds.

var loaderKey = [256]byte{}

var payloadURL = ""
